#!/usr/bin/env python2

import argparse
import getopt
import socket
import ssl
import sys

def countInstances(c, searchString):
  found_count = 0
  for char in searchString:
    if char == c:
      found_count += 1
  return found_count

def receiveMessage(sock):
  mes = ''
  while 1:
    data = sock.recv(4096)
    mes += data
    if data[-1] == '\n':
      #print('# received message')
      break
  #print(mes)
  return mes

def sendHello(sock, neuid):
  hello = 'cs3700fall2018 HELLO {}\n'.format(neuid)
  #print('# sending hello message: ' + hello)
  sock.sendall(hello)

def main():
  # Parse command line arguments
  parser = argparse.ArgumentParser(description='Simple client program')
  parser.add_argument('hostname')
  parser.add_argument('NEU ID')
  parser.add_argument('-p', dest='port', type=int)
  parser.add_argument('-s', action="store_true", default=False, dest='ssl')
  args = parser.parse_args(sys.argv[1:]) # arguments exclude filename
  #print(args) # for debug only delete before done

  hostname = args.hostname

  port = 27993
  if args.port:
    port = args.port
  elif args.ssl:
    port = 27994

  neuid = vars(args)['NEU ID']
  secretFlag = ''

  # Create a TCP/IP socket
  sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  if args.ssl:
    sock = ssl.wrap_socket(sock, ssl_version=ssl.PROTOCOL_TLSv1)

  remote_ip = socket.gethostbyname(hostname)
  #print('# Connecting to server, ' + hostname + ' (' + remote_ip + ')')
  
  sock.settimeout(5)
  sock.connect((hostname, port))

  #print("# Connected")

  #send HELLO message to the server
  sendHello(sock, neuid)

  while 1:

    message = receiveMessage(sock);
    message_list = message.split()

    if message_list[1] == "BYE":
      secretFlag = message_list[2]
      print(secretFlag)
      sock.close()
      break

    found_count = countInstances(message_list[2], message_list[3])

    count = 'cs3700fall2018 COUNT {}\n'.format(found_count)
    #print('# found {} instances of "{}" in the message'.format(found_count, message_list[2]))
    #print('# sending count message: ' + count)
    sock.sendall(count)

if __name__ == '__main__':
  main()
  