#!/usr/bin/python -u
#
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

MSG_SIZE = 1500
DATA_SIZE = 1000
TIMEOUT = 30
SEQUENCE = 0
buff = []


# Bind to localhost and an ephemeral port
IP_PORT = sys.argv[1]
UDP_IP = IP_PORT[0:IP_PORT.find(":")]
UDP_PORT = int(IP_PORT[IP_PORT.find(":")+1:])
dest = (UDP_IP, UDP_PORT)

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.settimeout(TIMEOUT)

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")


def send_next_packet():
  global SEQUENCE
  global buff

  data = sys.stdin.read(DATA_SIZE)
  if (len(data) > 0):
    msg = {"sequence": SEQUENCE, "data": data, "ack": False, "eof": False}
    SEQUENCE += len(data)

    buff.append(msg)

    msg = json.dumps(msg)
    if sock.sendto(msg, dest) < len(msg):
      log("[error] unable to fully send packet")
    else:
      log("[send data] " + str(SEQUENCE) + " (" + str(len(data)) + ")")
    return True
  else:
    return False

# Send all packets 
def send_all_data():
  global buff
  buff = []
  global SEQUENCE
  SEQUENCE = 0

  while send_next_packet():
    pass
  sock.sendto(json.dumps({"eof": True, "data": "", "sequence": SEQUENCE, "ack": False}), dest)

send_all_data()

# Now read in data, send packets
# resend data if we get two acks in a row for the same sequence number
lastack = 0
while True:
  log("ABOUT TO SLEEP")
  result = sock.recvfrom(MSG_SIZE) #receiving ACK

  if result:
    (data, addr) = result
    try:
      decoded = json.loads(data)

      if decoded['ack'] == buff[-1]['ack']:
        # were done woohoo
        break
      elif decoded['ack'] == lastack:
        log("[recv ack] " + str(lastack))
        # resend the data that comes after lastack
        msgtoresend = buff[buff.index([b for b in buff if b.sequence + len(b.data) == lastack][0]) + 1]
        if sock.sendto(msgtoresend, dest) < len(msgtoresend):
          log("[error] unable to fully send packet")
        else:
          log("[send data] " + str(lastack) + " (" + str(len(data)) + ")")

      lastack = decoded['ack']

    except (ValueError, KeyError, TypeError):
      log("[recv corrupt packet]")
  else:
    log("[error] timeout")
    send_all_data()

sock.sendto(json.dumps({"eof": True, "data": "", "sequence": SEQUENCE, "ack": False}), dest)
sys.exit(0)
