#!/usr/bin/python -u
#
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

def printMessageInOrder(buff):
  sequence = 0
  while True:
    entry = buff[sequence]
    if entry['eof']:
      log("[completed]")
      sys.exit(0)
    else:
      sys.stdout.write(entry['data'])
      sequence += len(entry['data'])

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = 0

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

buff = {}

# Now listen for packets
while True:

  result = sock.recvfrom(MSG_SIZE)

  # If nothing is ready, we hit the timeout
  if result:
    (data, addr) = result

    try:
      decoded = json.loads(data)

      # If the EOF flag is set, exit
      if (decoded['eof']):
        buff[decoded['sequence']] = decoded
        # log("[completed]")
        # sys.exit(0)

      # If there is data, we accept it and print it out
      if (decoded['data']):
        buff[decoded['sequence']] = decoded
        # If we receive data, we assume it's in-order
        # You will need to do much more here
        log("[recv data] " + str(decoded['sequence']) + " (" + str(len(decoded['data'])) + ") ACCEPTED (in-order)")
        # sys.stdout.write(decoded['data'])

      # Send back an ack to the sender
      msg = json.dumps({"ack": decoded['sequence'] + len(decoded['data'])})
      log("ABOUT TO SEND " + msg)
      if sock.sendto(msg, addr) < len(msg):
        log("[error] unable to fully send packet")

      # check if we can hop from 0 to eof
      sequence = 0
      while True:
        entry = buff.get(sequence)
        if entry is None:
          break
        elif entry['eof']:
          printMessageInOrder(buff)
        else:
          sequence += len(entry['data'])

    except (ValueError, KeyError, TypeError) as e:
      log("[recv corrupt packet]")
      raise e
  else:
    log("[error] timeout")
    sys.exit(-1)
