#!/usr/bin/python -u
#
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

MSG_SIZE = 1500

def printMessageInOrder(buff):
  sequence = 0
  while True:
    entry = buff[sequence]
    if entry['eof']:
      log("[completed]")
      sys.exit(0)
    else:
      sys.stdout.write(entry['data'])
      sequence += len(entry['data'])

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

def start_closing(buff):
  count = 0
  while count < 10:
    ready = select.select([sock], [sock], [], 0.1)
    if ready[0]: # new data from sender cas
      sock.recvfrom(MSG_SIZE)
      count = 0
    if ready[1]: # send ack case
      log("Resending eof ack")
      if sock.sendto(msg, addr) < len(msg):
        log("[error] unable to fully send packet")
      time.sleep(0.1)
    count += 1
  printMessageInOrder(buff)
  sys.exit(0)

TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = 0

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

buff = {}

# Now listen for packets
while True:

  result = sock.recvfrom(MSG_SIZE)

  # If nothing is ready, we hit the timeout
  if result:
    (data, addr) = result

    try:
      decoded = json.loads(data)

      # If the EOF flag is set, log and andd to buffer
      if (decoded['eof']):
        buff[decoded['sequence']] = decoded
        log("[eof] " + str(decoded['sequence']) + " (" + str(len(decoded['data'])) + ")" )

      # If there is data, we accept it and print it out
      if (decoded['data']):
        buff[decoded['sequence']] = decoded
        log("[recv data] " + str(decoded['sequence']) + " (" + str(len(decoded['data'])) + ") ACCEPTED")

      # Send back an ack to the sender (NOT SACK)
      sequence = 0
      preventry = None
      entry = {"sequence": 0, "data": ""}
      ackedmsg = None
      eof = 0
      while True:
        preventry = entry
        entry = buff.get(sequence)
        if entry is None:
          # send ack for previous entry
          ackedmsg = preventry
          break
        elif entry['sequence'] == decoded['sequence']:
          # send ack for entry
          ackedmsg = entry
          if decoded['eof']:
            eof = 1
          break
        else:
          sequence += len(entry['data'])

      msg = json.dumps({"ack": ackedmsg['sequence'] + len(ackedmsg['data']) + eof, 'timestamp':ackedmsg['timestamp']})
      log("ABOUT TO SEND " + msg)
      if sock.sendto(msg, addr) < len(msg):
        log("[error] unable to fully send packet")
      
      # make sure the sender gets this eof 
      if eof:
        start_closing(buff)

    except (ValueError, KeyError, TypeError) as e:
      log("[recv corrupt packet]")
      raise e
  else:
    log("[error] timeout")
    sys.exit(-1)
