#!/usr/bin/python -u

import argparse, socket, time, json, select, struct, math, string, copy

#DEBUG = True
DEBUG = False

parser = argparse.ArgumentParser(description='route packets')
parser.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
args = parser.parse_args()

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"

# other keys
ROUTERIP = 'routerip'
NTWKPRFX = 'networkprefix'
CIDR = 'cidr'
SRCIF = 'srcif'

##########################################################################################

# convert an ip address in a.b.c.d form to a binary string
def ip2bin(ipaddr):
    binvalue = ''.join(bin(int(x))[2:].zfill(8) for x in ipaddr.split('.'))
    return binvalue

# convert binary string to a.b.c.d ip address
def bin2ip(binaddr):
    ipparts = [int(binaddr[0:8], 2), 
               int(binaddr[8:16], 2), 
               int(binaddr[16:24], 2), 
               int(binaddr[24:32], 2)]
    return ".".join(str(ipp) for ipp in ipparts)

# convert a netmask ip address to a cidr int representation
def nmsk2cidr(nmsk):
    binip = ip2bin(nmsk)
    return string.count(binip.split('0')[0], '1')

# apply a netmask to a network, both in a.b.c.d form
def getprefix(ntwk, nmsk):
    ntwkbin = ip2bin(ntwk)
    cidr = nmsk2cidr(nmsk)
    return ntwkbin[0:cidr].ljust(32, '0')

class Router:

    routes = None
    updates = None
    relations = None
    sockets = None

    def __init__(self, networks):
        self.routes = []
        self.updates = []
        self.relations = {}
        self.sockets = {}
        for relationship in networks:
            network, relation = relationship.split("-")
            ip2bin(network)
            if DEBUG: 
                print "Starting socket for", network, relation
            self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
            self.sockets[network].setblocking(0)
            self.sockets[network].connect(network)
            self.relations[network] = relation
        return

    def lookup_routes(self, daddr):
        """ Lookup all valid routes for an address """
        outroutes = []
        
        # get binary representation of the destination address
        daddrbin = ip2bin(daddr)
        if DEBUG:
            print '++++++++++++++++++++++++++++++++++++++++++++++++++++'
            print 'DEST ADDR BIN ' + daddrbin

        # iterate over routes, selecting those whose first cidr digits match daddrbin
        longestcidr = -1
        for route in self.routes:
            routebin = ip2bin(route[NTWK])
            cidr = nmsk2cidr(route[NMSK])
            if DEBUG:
                print 'CIDR ' + str(cidr)
                print 'ROUTE BIN ' + routebin 
            # if the route address matches the destination address, update outroutes
            if (daddrbin[0:cidr] == routebin[0:cidr]):
                # if the netmask of the ne new route is longer than the 
                # previously found routes, only match the new route
                if (cidr > longestcidr):
                    longestcidr = cidr
                    outroutes = [route]
                # otherwaise go ahead and add the new route to outroutes (multiple matches)
                elif (cidr == longestcidr):
                    outroutes.append(route)
        if DEBUG:
            print 'OUTROUTES ' + json.dumps(outroutes)
            print '++++++++++++++++++++++++++++++++++++++++++++++++++++'
        return outroutes

    def get_shortest_as_path(self, routes):
        """ select the route with the shortest AS Path """
        outroutes = []
        minval = min([len(r[APTH]) for r in routes])
        
        for r in routes:
            if len(r[APTH]) == minval:
                outroutes.append(r)
        return outroutes
            
    def get_highest_preference(self, routes):
        """ select the route with the shortest AS Path """
        outroutes = []
        maxVal = max([r[LPRF] for r in routes])
        
        for r in routes:
            if r[LPRF] == maxVal:
                outroutes.append(r)
        return outroutes
         
    def get_self_origin(self, routes):
        """ select self originating routes """
        outroutes = []
        for r in routes:
            if r[SORG] == 'True':
                outroutes.append(r)
        if len(outroutes) == 0: 
            return routes
        return outroutes

    def get_origin_routes(self, routes):
        """ select origin routes: EGP > IGP > UNK """
        outroutes = []
        if 'IGP' in [r[ORIG] for r in routes]:
            outroutes = [r for r in routes if r[ORIG] == 'IGP']
        elif 'EGP' in [r[ORIG] for r in routes]:
            outroutes = [r for r in routes if r[ORIG] == 'EGP']
        else:
            outroutes = routes
        return outroutes

    def get_lowest_ip_address(self, routes):
        """ select route with lowest ip address """
        rmin = min([map(int, r[PEER].split('.')) for r in routes])
        return [r for r in routes if map(int, r[PEER].split('.')) == rmin]

    def filter_relationships(self, srcif, routes):
        """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
        outroutes = []
        if DEBUG:
            print self.relations
        for r in routes:
            if self.relations[srcif] == CUST or self.relations[r[PEER]] == CUST:
                outroutes.append(r)
                    
        return outroutes

    def get_route(self, srcif, daddr):
        """ Select the best route for a given address   """
        peer = None
        routes = self.lookup_routes(daddr)
        
        if routes:
            # 1. Highest Preference
            routes = self.get_highest_preference(routes)
            # 2. Self Origin
            routes = self.get_self_origin(routes)
            # 3. Shortest ASPath
            routes = self.get_shortest_as_path(routes)
            # 4. EGP > IGP > UNK
            routes = self.get_origin_routes(routes)
            # 5. Lowest IP Address
            routes = self.get_lowest_ip_address(routes)
            # Final check: enforce peering relationships
            routes = self.filter_relationships(srcif, routes)

        if DEBUG:
            print "All Routes Found:"
            print routes

        if len(routes) == 0:
            return None
        
        peer = routes[0]['peer']     
        return self.sockets[peer] if peer else None

    def forward(self, srcif, packet):
        """ Forward a data packet   """
        # find the route
        route = self.get_route(srcif, packet[DEST])
        if route: 
            # if the route exists, forward the packet
            route.send(json.dumps(packet))
        else:
            # if the route does not exist, send a NO ROUTE message to the sender
            newpacket = {
                SRCE: [r[ROUTERIP] for r in self.routes if r[PEER] == srcif][0],
                DEST: packet[SRCE],
                TYPE: NRTE,
                MESG: {}}
            self.sockets[srcif].send(json.dumps(newpacket))
        return True

    def coalesce(self):
        """ coalesce any routes that are right next to each other   """
        # iterate from cidr nmsk 32 down to cidr nmsk 0
        for c in reversed(range(0, 32)): 
            # find all routes with same cidr (candidates to get coalesced)
            matched = [r for r in self.routes if r[CIDR] == c]
    
            # check every matched against every other matched and check if they can be coalexed
            for i in range(len(matched)):
                for j in range(i+1, len(matched)):
                    # if all bits match in the network prefix other than the last
                    # AND the next hop is the same, we can coalesce
                    if (matched[i][NTWKPRFX][0:c-1] == matched[j][NTWKPRFX][0:c-1] 
                        and matched[i][PEER] == matched[j][PEER]):
                        if DEBUG:
                            print "Found a coalesce match"
                            print matched[i]
                            print matched[j]
                        # we can coalesce i and j!
                        # modify matched[i]
                        matched[i][CIDR] = c - 1
                        matched[i][NTWKPRFX] = matched[i][NTWKPRFX][0:c-1].ljust(32, '0')
                        matched[i][NTWK] = bin2ip(matched[i][NTWKPRFX])
                        matched[i][NMSK] = bin2ip(''.ljust(c-1, '1').ljust(32, '0'))
                        # remove matched[j] from self.routes
                        self.routes.remove(matched[j])        
        return True

    def update(self, srcif, packet, quiet=False):
        """ handle update packets   """
                                                                             # add additional information into the route entry
        routeentry = copy.deepcopy(packet[MESG])
        routeentry[PEER] = srcif                                             # the peer
        routeentry[ROUTERIP] = packet[DEST]                                  # OUR IP address for this route
        routeentry[NTWKPRFX] = getprefix(routeentry[NTWK], routeentry[NMSK]) # the network prefix
        routeentry[CIDR] = nmsk2cidr(routeentry[NMSK])                       # cidr representation of the netmask

        self.routes.append(routeentry) # add the route to our routes
        
        # quiet mode is for internal route updates
        # e.g. rebuilding the routes table after disaggregation
        # in this case, we don't want to notify neighbors of the update
        # and we don't want to coalesce (will be performed once after disagg)
        if not quiet:
            packet[SRCIF] = srcif                        # save the srcif on the packet for use in disagg
            self.updates.append(packet)                  # store the update
            for (network, sock) in self.sockets.items(): # for each neighbor
                if network == packet[SRCE]:              # don't send update to who gave it to us
                    if DEBUG:
                        print 'Not sending update to origin'
                elif self.relations[packet[SRCE]] == CUST or self.relations[network] == CUST: 
                    # send update message to EVERYONe if the update comes from customer
                    # send update message to our customers always
                    if DEBUG:
                        print 'Forwarding update message'
                    newpacket = {SRCE: packet[DEST],
                        DEST: network,
                        TYPE: UPDT,
                        MESG: packet[MESG]}
                    sock.send(json.dumps(newpacket))
        
            # coalesce after all this updating
            self.coalesce()

        return True
    
    def revoke(self, packet):
        """ handle revoke packets   """
        self.updates.append(packet)  # save the update
        self.routes = []             # clear out the routes so we can rebuild the table
        for update in self.updates:  # for each update
            if update[TYPE] == UPDT: # if its an update, just perform UPDATE in quiet mode
                self.update(update[SRCIF], update, quiet=True)
            if update[TYPE] == RVKE: # if its a revoke, remove the requested route
                for entry in update[MESG]:
                    self.routes = [r for r in self.routes if r[NTWK] != entry[NTWK]
                            or r[NMSK] != entry[NMSK]
                            or packet[SRCE] != r[PEER]]
        
        # after rebuilding the table naively, then do coalescing (disaggregation)
        self.coalesce()

        # notify neighbors of revoke (same logic as update())
        for (network, sock) in self.sockets.items():
            if network == packet[SRCE]:
                if DEBUG:
                    print 'NOT SENDING revoke update'
            elif self.relations[packet[SRCE]] == CUST or self.relations[network] == CUST:
                if DEBUG:
                    print 'Forwarding revoke message'
                newpacket = {SRCE: packet[DEST],
                        DEST: network,
                        TYPE: RVKE,
                        MESG: packet[MESG]}
                sock.send(json.dumps(newpacket))
        return True

    def dump(self, packet):
        """ handles dump table requests """
        msg = [{NTWK: x[NTWK], NMSK: x[NMSK], PEER: x[PEER]} for x in self.routes]
        newpacket = {
            SRCE: packet[DEST],
            DEST: packet[SRCE],
            TYPE: TABL,
            MESG: msg}

        self.sockets[packet[SRCE]].send(json.dumps(newpacket))
        return True

    def handle_packet(self, srcif, packet):
        """ dispatches a packet """
        if packet[TYPE] == UPDT:
            return self.update(srcif, packet)
        if packet[TYPE] == DATA:
            return self.forward(srcif, packet)    
        if packet[TYPE] == DUMP:
            return self.dump(packet)
        if packet[TYPE] == RVKE:
            return self.revoke(packet)
        return False

    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                try:
                    k = conn.recv(65535)
                except:
                    # either died on a connection reset, or was SIGTERM's by parent
                    return
                if k:
                    for sock in self.sockets:
                        if self.sockets[sock] == conn:
                            srcif = sock
                    msg = json.loads(k)
                    if DEBUG:
                        print "Type: " + msg['type']
                        print "Src:" + msg['src']
                        print "Dst:" + msg['dst']
                        print "Msg:" + json.dumps(msg['msg'])
                        print "=================="
                    self.handle_packet(srcif, msg)
                else:
                    return
        return

if __name__ == "__main__":
    router = Router(args.networks)
    router.run()
